stages:
  - install
  - test
  - build
  - deploy

install_dependencies:
  stage: install
  image: node:latest
  script:
      - npm install 
  cache:
    paths:
      - node_modules/  

test: 
    image: node:latest
    stage: test
    script:
    - echo "Make tests"

build:
  stage: build
  image: node:latest
  script:
    - echo "Building ..."
    - npm run build  
  artifacts:
    paths:
      - build/ 
    expire_in: 1 hour  

deploy:
  stage: deploy
  script: 
    - echo "Deploying to production..."
  only:
    - master

