apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      imagePullSecrets:
      - name: ghcr-token
      containers:
      - name: weather-app
        image: ghcr.io/jrkarmau/weather-app:$IMAGE_TAG
        env:
          - name: REACT_APP_OPENWEATHER_API_KEY
            valueFrom:
              secretKeyRef:
                name: weather-secrets
                key: openweather-api-key
          - name: REACT_APP_WEATHERAPI_API_KEY
            valueFrom:
              secretKeyRef:
                name: weather-secrets
                key: weatherapi-api-key
        ports:
        - containerPort: 3000
