name: Docker Image CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag weather-app:$(date +%s)

    - name: Run Docker container
      run: docker run -d -p 3000:3000 weather-app

  tests: 

    needs: build
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4

    - name: Run unit tests #every test.js file
      run: npm test 

    - name: Install Playwright for E2E tests
      run: npx playwright install --with-deps

    - name: Run E2E tests
      run: echo "running more tests"
     #  run: npx playwright test tests/e2e.test.js
