name: Docker Image CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: >-
        docker build .
        --file Dockerfile.development
        --tag ghcr.io/jrkarmau/weather-app:development
        --secret id=REACT_APP_OPENWEATHER_API_KEY
        --secret id=REACT_APP_WEATHERAPI_API_KEY
      env:
        REACT_APP_OPENWEATHER_API_KEY: ${{ secrets.REACT_APP_OPENWEATHER_API_KEY }}
        REACT_APP_WEATHERAPI_API_KEY: ${{ secrets.REACT_APP_WEATHERAPI_API_KEY }}

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u jrkarmau --password-stdin

    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/jrkarmau/weather-app:latest

#    - name: Run Docker container
#      run: |
#        docker run -d -p 3000:3000 \
#          -e REACT_APP_OPENWEATHER_API_KEY=${{ secrets.REACT_APP_OPENWEATHER_API_KEY }} \
#          -e REACT_APP_WEATHERAPI_API_KEY=${{ secrets.REACT_APP_WEATHERAPI_API_KEY }} \
#          ghcr.io/jrkarmau/weather-app:latest