name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release (e.g., v1.2.3)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GHCR_PULL_TOKEN }}
          script: |
            const tag = '${{ inputs.tag }}';
            const response = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: `Release ${tag}`,
              body: `Automated release for ${tag}.`,
              draft: false,
              prerelease: false,
              generate_release_notes: true
            });
            console.log(`Release created: ${response.data.html_url}`);
