name: Run Tests

on:
  push:
    branches: [ "main", "development", "feature/*" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:

  tests:

    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: npm ci and build
      run: |
        npm ci
        npm run build

    - name: Run unit tests
      run: npm test

    - name: Run E2E tests
      uses: cypress-io/github-action@v6
      with:
        start: npm start
        wait-on: 'http://localhost:3000'
      env:
        REACT_APP_OPENWEATHER_API_KEY: ${{ secrets.REACT_APP_OPENWEATHER_API_KEY }}
        REACT_APP_WEATHERAPI_API_KEY: ${{ secrets.REACT_APP_WEATHERAPI_API_KEY }}